### ISSUE TITLE
Spike: Investigate why TCR is only stamping COVID codes on ECR's

### ISSUE THREAD

**Issue by nickbristow** [CDCgov/phdi#2114] opened 2024-07-11 18:39 UTC
## Action Requested
Currently, the trigger code reference is only stamping our ECR's with covid. We need it to stamp illness based on the RR when using the orchestration service.

Investigate why this is happening.

## Acceptance Criteria
- Reason for this behaviour is known
- Plan for fix is in place

**Comment by angelathe** [comment] 2024-07-11 20:03
Note: In `seed-ecr-viewer-config.json`, we have to manually list the condition codes to get stamped under the `/stamp-condition-extensions` endpoint

**Comment by gordonfarrell** [comment] 2024-07-12 15:20
I think we know why this is happening already, gonna write a ticket for the fix after a quick confirmation

**Comment by gordonfarrell** [comment] 2024-07-12 21:18
Closing this, confirmed the reason and wrote tickets addressing the issue

**Closed by gordonfarrell** 2024-07-12 21:18 UTC
Labels: spike, Streamline eCR
