### ISSUE TITLE
Insert ValueSet into DB

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi#2793] opened 2024-10-18 14:45 UTC
Write a function that given an instance of `ValueSet` will insert the contents of the valueset into our database.

**Comment by fzhao99** [comment] 2024-10-21 13:57
dupe of https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/cdcgov/dibbs-query-connector/38

**Closed by fzhao99** 2024-10-21 13:57 UTC
Labels: viper
